routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\WebHookController;
use App\Http\Controllers\Api\InboxesController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('inbox', [InboxesController::class, 'handle']);

Route::get('/is_curl', function() {
   function file_get_contents_with_curl($url)
    {
      $ch = curl_init();
      $timeout = 5;
      curl_setopt($ch,CURLOPT_URL,$url);
      curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
      curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
      $data = curl_exec($ch);
      curl_close($ch);
      return $data;
    }
    
    $contents = file_get_contents_with_curl("http://www.husmodata.com/api/data/");
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/testapi', function () {
    return view('test');
});


Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/dashboard/{token}', 'HomeController@show')->name('show');

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/transactions', 'TransactionController@index')->name('transactions');
Route::get('/topups', 'TransactionController@topup')->name('topups');
Route::post('profile-picture', 'ProfileController@profilePicture');
Route::get('/reset-password', 'HomeController@resetPassword')->name('reset-password');
// Route::get('/history', 'HistoryController@index')->name('history');
Route::get('/topup', 'TopupController@index')->name('topup');
Route::get('/buy', 'BuyController@index')->name('buys');
Route::post('/buy', 'BuyController@buy')->name('buy');
Route::get('/confirm', 'BuyController@getConfirm')->name('confirms');
Route::post('/confirm', 'BuyController@postConfirm')->name('confirm');
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
Route::get('FundWallet/{data}', 'PaymentController@FundWallet')->name('fund');
Route::get('/callback', 'PaymentController@handleGatewayCallback')->name('callback');
Route::get('/finish', 'PaymentController@finish')->name('finish');
Route::get('/fetch-products/{id}', 'BuyController@fetchProducts');
Route::get('/fetch-price/{id}', 'BuyController@fetchPrice');

Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::get('/dashboard', 'HomeController@dashboard')->name('admin.dashboard');
	Route::get('/profile', 'HomeController@profile')->name('admin.profile');
	Route::get('/reset-password', 'HomeController@resetPassword')->name('admin.reset-password');
	Route::get('/agents', 'HomeController@agents')->name('admin.agents');
	Route::get('purchases/approve/{id}', 'PurchaseController@approve');
	Route::resource('purchases', 'PurchaseController');
	Route::resource('categories', 'CategoryController');
	Route::resource('products', 'ProductController');
	Route::resource('users', UserController::class)->except(['create', 'store']);
	Route::resource('agents', 'AgentController')->except(['create', 'store']);
});

require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Bavix\Wallet\Interfaces\Customer;
use Bavix\Wallet\Interfaces\Product as Item;
use Bavix\Wallet\Traits\HasWallet;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements Item
{
    use HasFactory, HasWallet;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function canBuy(Customer $customer, int $quantity = 1, bool $force = null): bool
    {
        /**
         * If the service can be purchased once, then
         *  return !$customer->paid($this);
         */
        return true; 
    }

    public function getAmountProduct(Customer $customer)
    {
        return $this->price;
    }

    public function getMetaProduct(): ?array
    {
        return [
            'title' => $this->name, 
            'description' => 'Purchase of Product #' . $this->name,
        ];
    }
    
    public function getUniqueId(): string
    {
        return (string)$this->getKey();
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('category')->get();
        
        return view('admin.settings.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        return view('admin.settings.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'category_id' => 'required',
            'name' => 'required|unique:products',
            'price' => 'required',
            'description' => 'required',
            'validity' => 'required',
            'type' => 'required'
        ]);

        $product = Product::create([
            'category_id' => $request->category_id,
            'name' => $request->name,
            'price' => $request->price,
            'description' => $request->description,
            'validity' => $request->validity,
            'type' => $request->type,
        ]);

        return redirect()->back()->with('message', 'Product created successfully!');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::pluck('name', 'id');
        return view('admin.settings.product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->validate(request(), [
            'category_id' => 'required',
            'name' => 'required',
            'price' => 'required',
            'description' => 'required',
            'validity' => 'required',
            'type' => 'requuired'
        ]);


        $product->update($request->all());

        return redirect()->route('products.index')->with('message', 'Product updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect()->back()->with('message', 'Product deleted successfully!');
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/settings/product/create.blade.php
<x-app-layout>
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                        Products
                    </h2>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <!-- BEGIN: Input -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200 dark:border-dark-5">
                                <h2 class="font-medium text-base mr-auto">
                                    Create Product
                                </h2>
                                <div class="form-check w-full sm:w-auto sm:ml-auto mt-3 sm:mt-0">
                                    <a href="{{ route('products.index') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="list" class="w-4 h-4 mr-3"></i> List Products </a>
                                </div>
                            </div>
                            <div id="input" class="p-5">
                                <div class="preview">
                                    <form method="POST" action="{{ route('products.store') }}">
                                        @csrf
                                        @include('admin.settings.product.form', ['submitButtonText' => 'Save'])
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- END: Input -->
                        
                    </div>
                </div>           
</x-app-layout>

resources/views/admin/settings/product/edit.blade.php
<x-app-layout>
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                        Products
                    </h2>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <!-- BEGIN: Input -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200 dark:border-dark-5">
                                <h2 class="font-medium text-base mr-auto">
                                    Create Product
                                </h2>
                                <div class="form-check w-full sm:w-auto sm:ml-auto mt-3 sm:mt-0">
                                    <a href="{{ route('products.index') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="list" class="w-4 h-4 mr-3"></i> List Products </a>
                                </div>
                            </div>
                            <div id="input" class="p-5">
                                <div class="preview">
                                    {!! Form::model($product, ['method' => 'PATCH', 'route' => ['products.update', $product->id]]) !!}
                                        @csrf
                                        @include('admin.settings.product.form', ['submitButtonText' => 'Update'])
                                    {!! Form::close() !!}   
                                </div>
                            </div>
                        </div>
                        <!-- END: Input -->
                        
                    </div>
                </div>           
</x-app-layout>

resources/views/admin/settings/product/form.blade.php
<div>
    {!! Form::label('category_id', 'Network') !!}
    {!! Form::select('category_id', $categories, isset($inputs['category_id']) ? $inputs['category_id'] : null, ['id' => 'category_id',  'class' => $errors->first('category_id') ? ' form-select mt-2 sm:mr-2 border-theme-6' : 'form-select mt-2 sm:mr-2']) !!}
    @error('category_id')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<div>
    {!! Form::label('type', 'Type') !!}
    {!! Form::select('type', ['user' => 'User', 'agent' => 'Agent'], isset($inputs['type']) ? $inputs['type'] : null, ['id' => 'type',  'class' => $errors->first('category_id') ? ' form-select mt-2 sm:mr-2 border-theme-6' : 'form-select mt-2 sm:mr-2']) !!}
    @error('type')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<div>
    {!! Form::label('name', 'Name', ['class' => 'form-label']) !!}
    {!! Form::text('name', isset($inputs['name']) ? $inputs['name'] : null, ['id' => 'name', 'class' => $errors->first('name') ? ' form-control border-theme-6' : 'form-control', 'placeholder' => 'Enter name']) !!}
    @error('name')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>
<div>
    {!! Form::label('price', 'Price', ['class' => 'form-label']) !!}
    {!! Form::text('price', isset($inputs['price']) ? $inputs['price'] : null, ['id' => 'price', 'class' => $errors->first('price') ? ' form-control border-theme-6' : 'form-control', 'placeholder' => 'Enter price']) !!}
    @error('price')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<div>
    {!! Form::label('description', 'Description', ['class' => 'form-label']) !!}
    {!! Form::text('description', isset($inputs['description']) ? $inputs['description'] : null, ['id' => 'description', 'class' => $errors->first('description') ? ' form-control border-theme-6' : 'form-control', 'placeholder' => 'Enter description']) !!}
    @error('description')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<div>
    {!! Form::label('validity', 'Validity', ['class' => 'form-label']) !!}
    {!! Form::text('validity', isset($inputs['validity']) ? $inputs['validity'] : null, ['id' => 'validity', 'class' => $errors->first('validity') ? ' form-control border-theme-6' : 'form-control', 'placeholder' => 'Enter validity']) !!}
    @error('validity')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<button type="submit" class="btn btn-primary mt-5">{{ $submitButtonText }}</button>

resources/views/admin/settings/product/index.blade.php
<x-app-layout>
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center h-10">
                                    <h2 class="text-lg font-medium truncate mr-5">
                                        Products
                                    </h2>
                                    <a href="{{ route('products.create') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="plus" class="w-4 h-4 mr-3"></i> Add New Category </a>
                                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <!-- BEGIN: Data List -->
                    <div class="intro-y col-span-12 lg:col-span-12">
                        <!-- BEGIN: Basic Table -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
                                <h2 class="font-medium text-base mr-auto">
                                    Products
                                </h2>
                            </div>
                            <div class="p-5" id="basic-table">
                                <div class="preview">
                                    <div class="overflow-x-auto">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">#</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Network</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Type</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Name</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Price</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Validity</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Status</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap items-right">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($products as $sn => $product)
                                                    <tr>
                                                        <td class="border-b dark:border-dark-5">{{ $sn + 1 }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $product->category->name }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $product->type }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $product->name }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $product->price }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $product->validity }}</td>
                                                        <td class="border-b dark:border-dark-5">
                                                        @if($product->status == 0)
                                                            <span class="text-theme-6">     Inactive 
                                                            </span>
                                                        @else
                                                            <span class="text-theme-9">     Active
                                                            </span>
                                                        @endif
                                                        </td>
                                                        <td class="border-b dark:border-dark-5">
                                                            <div class="flex">
                                                                <a href="{{ url('admin/products/' .$product->id . '/edit') }}" class="flex mr-3">
                                            <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit
                                        </a>
                                                                {!! Form::open(['method' => 'DELETE', 'url' => 'admin/products/' . $product->id]) !!}
                                        
                                        <button type="submit" class="flex text-theme-6" onclick="return confirm('Are you sure?')"><i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete</button>
                                        
                                        {!! Form::close() !!}
                                                        </div>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                        
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <!-- END: Basic Table -->
                        
                    </div>
                   
                </div>            
</x-app-layout>