routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\WebHookController;
use App\Http\Controllers\Api\InboxesController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('inbox', [InboxesController::class, 'handle']);

Route::get('/is_curl', function() {
   function file_get_contents_with_curl($url)
    {
      $ch = curl_init();
      $timeout = 5;
      curl_setopt($ch,CURLOPT_URL,$url);
      curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
      curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
      $data = curl_exec($ch);
      curl_close($ch);
      return $data;
    }
    
    $contents = file_get_contents_with_curl("http://www.husmodata.com/api/data/");
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/testapi', function () {
    return view('test');
});


Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/dashboard/{token}', 'HomeController@show')->name('show');

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/transactions', 'TransactionController@index')->name('transactions');
Route::get('/topups', 'TransactionController@topup')->name('topups');
Route::post('profile-picture', 'ProfileController@profilePicture');
Route::get('/reset-password', 'HomeController@resetPassword')->name('reset-password');
// Route::get('/history', 'HistoryController@index')->name('history');
Route::get('/topup', 'TopupController@index')->name('topup');
Route::get('/buy', 'BuyController@index')->name('buys');
Route::post('/buy', 'BuyController@buy')->name('buy');
Route::get('/confirm', 'BuyController@getConfirm')->name('confirms');
Route::post('/confirm', 'BuyController@postConfirm')->name('confirm');
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
Route::get('FundWallet/{data}', 'PaymentController@FundWallet')->name('fund');
Route::get('/callback', 'PaymentController@handleGatewayCallback')->name('callback');
Route::get('/finish', 'PaymentController@finish')->name('finish');
Route::get('/fetch-products/{id}', 'BuyController@fetchProducts');
Route::get('/fetch-price/{id}', 'BuyController@fetchPrice');

Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::get('/dashboard', 'HomeController@dashboard')->name('admin.dashboard');
	Route::get('/profile', 'HomeController@profile')->name('admin.profile');
	Route::get('/reset-password', 'HomeController@resetPassword')->name('admin.reset-password');
	Route::get('/agents', 'HomeController@agents')->name('admin.agents');
	Route::get('purchases/approve/{id}', 'PurchaseController@approve');
	Route::resource('purchases', 'PurchaseController');
	Route::resource('categories', 'CategoryController');
	Route::resource('products', 'ProductController');
	Route::resource('users', UserController::class)->except(['create', 'store']);
	Route::resource('agents', 'AgentController')->except(['create', 'store']);
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'status'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class CategoryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        
        return view('admin.settings.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.settings.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(), [
            'name' => 'required|unique:categories'
        ]);

        $category = Category::create(
            ['name' => $request->name]
        );

        return redirect()->back()->with('message', 'Category created successfully!');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.settings.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validate(request(), [
            'name' => 'required|unique:categories,name,' . $category->id,
        ]);


        $category->update($request->all());

        return redirect()->route('categories.index')->with('message', 'Category updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->back()->with('message', 'Category deleted successfully!');
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/settings/category/create.blade.php
<x-app-layout>
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                        Categories
                    </h2>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <!-- BEGIN: Input -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200 dark:border-dark-5">
                                <h2 class="font-medium text-base mr-auto">
                                    Create Category
                                </h2>
                                <div class="form-check w-full sm:w-auto sm:ml-auto mt-3 sm:mt-0">
                                    <a href="{{ route('categories.index') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="list" class="w-4 h-4 mr-3"></i> List Categories </a>
                                </div>
                            </div>
                            <div id="input" class="p-5">
                                <div class="preview">
                                    <form method="POST" action="{{ route('categories.store') }}">
                                        @csrf
                                        @include('admin.settings.category.form', ['submitButtonText' => 'Save'])
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- END: Input -->
                        
                    </div>
                </div>           
</x-app-layout>

resources/views/admin/settings/category/edit.blade.php
<x-app-layout>
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center mt-8">
                    <h2 class="text-lg font-medium mr-auto">
                        Categories
                    </h2>
                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <!-- BEGIN: Input -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200 dark:border-dark-5">
                                <h2 class="font-medium text-base mr-auto">
                                    Create Category
                                </h2>
                                <div class="form-check w-full sm:w-auto sm:ml-auto mt-3 sm:mt-0">
                                    <a href="{{ route('categories.index') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="list" class="w-4 h-4 mr-3"></i> List Categories </a>
                                </div>
                            </div>
                            <div id="input" class="p-5">
                                <div class="preview">
                                    {!! Form::model($category, ['method' => 'PATCH', 'route' => ['categories.update', $category->id]]) !!}
                                        @csrf
                                        @include('admin.settings.category.form', ['submitButtonText' => 'Update'])
                                    {!! Form::close() !!}   
                                </div>
                            </div>
                        </div>
                        <!-- END: Input -->
                        
                    </div>
                </div>           
</x-app-layout>

resources/views/admin/settings/category/form.blade.php
<div>
    {!! Form::label('name', 'Name', ['class' => 'form-label']) !!}
    {!! Form::text('name', isset($inputs['name']) ? $inputs['name'] : null, ['id' => 'name', 'class' => $errors->first('name') ? ' form-control border-theme-6' : 'form-control', 'placeholder' => 'Enter name']) !!}
    @error('name')
        <div class="text-theme-6 mt-2">{{ $message }}</div>
    @enderror
</div>

<button type="submit" class="btn btn-primary mt-5">{{ $submitButtonText }}</button>

resources/views/admin/settings/category/index.blade.php
<x-app-layout>
    @push('styles')
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.css"/>
    @endpush
    <!-- END: Top Bar -->
                <div class="intro-y flex items-center h-10">
                                    <h2 class="text-lg font-medium truncate mr-5">
                                        Categories
                                    </h2>
                                    <a href="{{ route('categories.create') }}" class="ml-auto flex items-center text-theme-1 dark:text-theme-10"> <i data-feather="plus" class="w-4 h-4 mr-3"></i> Add New Category </a>
                                </div>
                <div class="grid grid-cols-12 gap-6 mt-5">
                    <!-- BEGIN: Data List -->
                    <div class="intro-y col-span-12 lg:col-span-12">
                        <!-- BEGIN: Basic Table -->
                        <div class="intro-y box">
                            <div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
                                <h2 class="font-medium text-base mr-auto">
                                    Categories
                                </h2>
                            </div>
                            <div class="p-5" id="basic-table">
                                <div class="preview">
                                    <div class="overflow-x-auto">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">#</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Name</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Status</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap items-right">Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($categories as $sn => $category)
                                                    <tr>
                                                        <td class="border-b dark:border-dark-5">{{ $sn + 1 }}</td>
                                                        <td class="border-b dark:border-dark-5">{{ $category->name }}</td>
                                                        <td class="border-b dark:border-dark-5">
                                                        @if($category->status == 0)
                                                            <span class="text-theme-6">     Inactive 
                                                            </span>
                                                        @else
                                                            <span class="text-theme-9">     Active
                                                            </span>
                                                        @endif
                                                        </td>
                                                        <td class="border-b dark:border-dark-5">
                                                            <div class="flex">
                                                                <a href="{{ url('categories/' .$category->id . '/edit') }}" class="flex mr-3">
                                            <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit
                                        </a>
                                                                {!! Form::open(['method' => 'DELETE', 'url' => 'admin/categories/' . $category->id]) !!}
                                        
                                        <button type="submit" class="flex text-theme-6" onclick="return confirm('Are you sure?')"><i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete</button>
                                        
                                        {!! Form::close() !!}
                                                        </div>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                
                                            </tbody>
                                        </table>
                                        
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <!-- END: Basic Table -->
                        
                    </div>
                   
                </div>
@push('scripts') 
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.22/datatables.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#example').DataTable();
        });
    </script>
@endpush                   
</x-app-layout>