routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\WebHookController;
use App\Http\Controllers\Api\InboxesController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('inbox', [InboxesController::class, 'handle']);

Route::get('/is_curl', function() {
   function file_get_contents_with_curl($url)
    {
      $ch = curl_init();
      $timeout = 5;
      curl_setopt($ch,CURLOPT_URL,$url);
      curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
      curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
      $data = curl_exec($ch);
      curl_close($ch);
      return $data;
    }
    
    $contents = file_get_contents_with_curl("http://www.husmodata.com/api/data/");
});

Route::get('/', function () {
    return view('welcome');
});

Route::get('/testapi', function () {
    return view('test');
});


Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
Route::get('/dashboard/{token}', 'HomeController@show')->name('show');

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::get('/transactions', 'TransactionController@index')->name('transactions');
Route::get('/topups', 'TransactionController@topup')->name('topups');
Route::post('profile-picture', 'ProfileController@profilePicture');
Route::get('/reset-password', 'HomeController@resetPassword')->name('reset-password');
// Route::get('/history', 'HistoryController@index')->name('history');
Route::get('/topup', 'TopupController@index')->name('topup');
Route::get('/buy', 'BuyController@index')->name('buys');
Route::post('/buy', 'BuyController@buy')->name('buy');
Route::get('/confirm', 'BuyController@getConfirm')->name('confirms');
Route::post('/confirm', 'BuyController@postConfirm')->name('confirm');
Route::post('/pay', 'PaymentController@redirectToGateway')->name('pay');
Route::get('FundWallet/{data}', 'PaymentController@FundWallet')->name('fund');
Route::get('/callback', 'PaymentController@handleGatewayCallback')->name('callback');
Route::get('/finish', 'PaymentController@finish')->name('finish');
Route::get('/fetch-products/{id}', 'BuyController@fetchProducts');
Route::get('/fetch-price/{id}', 'BuyController@fetchPrice');

Route::namespace("Admin")->prefix('admin')->group(function(){
	Route::get('/dashboard', 'HomeController@dashboard')->name('admin.dashboard');
	Route::get('/profile', 'HomeController@profile')->name('admin.profile');
	Route::get('/reset-password', 'HomeController@resetPassword')->name('admin.reset-password');
	Route::get('/agents', 'HomeController@agents')->name('admin.agents');
	Route::get('purchases/approve/{id}', 'PurchaseController@approve');
	Route::resource('purchases', 'PurchaseController');
	Route::resource('categories', 'CategoryController');
	Route::resource('products', 'ProductController');
	Route::resource('users', UserController::class)->except(['create', 'store']);
	Route::resource('agents', 'AgentController')->except(['create', 'store']);
});

require __DIR__.'/auth.php';

app/Http/Livewire/Base.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class Base extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';


    public $sortDirection = 'asc';

    public $perPage = 10;

    public $search = '';

    public function updatingSearch()
    {
        $this->resetPage();
    }


    public function sortBy($field)
    {
        if ($this->sortDirection == 'asc') {
            $this->sortDirection == 'desc';
        } else {
            $this->sortDirection == 'asc';
        }
        return $this->sortBy = $field;
    }
}

app/Http/Livewire/Users.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class Users extends Base
{
    public $sortBy = 'name';
    public function render()
    {

        if ($this->search) {
            $users = User::query()
            
                ->where('name', 'like', '%' . $this->search . '%')
                ->Orwhere('email', 'like', '%' . $this->search . '%')
                ->Orwhere('phone', 'like', '%' . $this->search . '%')
                ->paginate(10);

            return view(
                'livewire.users',
                ['users' => $users]
            );
        } else {
            $users = User::query()
                ->orderBy($this->sortBy, $this->sortDirection)
                ->paginate($this->perPage);
            return view(
                'livewire.users',
                ['users' => $users]
            );
        }
    }
}

resources/views/livewire/users.blade.php
<div>
    <div class="intro-y flex items-center h-10">
        <h2 class="text-lg font-medium truncate mr-5">
            Users
        </h2>
        
    </div>
<div class="grid grid-cols-12 gap-6 mt-5">
<!-- BEGIN: Data List -->
<div class="intro-y col-span-12 lg:col-span-12">
<!-- BEGIN: Basic Table -->
<div class="intro-y box">
<div class="flex flex-col sm:flex-row items-center p-5 border-b border-gray-200">
    <h2 class="font-medium text-base mr-auto">
        Users
    </h2>
    <div class="col-md-3">
    <input type="search" wire:model.debounce.300ms='search'  class="form-control" Placeholder="Search ..">
    </div>
</div>
<div class="p-5" id="basic-table">
    <div class="preview">
        <div class="overflow-x-auto">
            <table class="table">
                <thead>
                    <tr>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">#</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Name</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Email</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Balance</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Phone Number</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Created At</th>
                        <th class="border-b-2 dark:border-dark-5 whitespace-nowrap items-right">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $sn => $user)
                        <tr>
                            <td class="border-b dark:border-dark-5">{{ $sn + 1 }}</td>
                            <td class="border-b dark:border-dark-5">{{ $user->name }}</td>
                            <td class="border-b dark:border-dark-5">{{ $user->email }}</td>
                            <td class="border-b dark:border-dark-5">{{ $user->balance }}</td>
                            <td class="border-b dark:border-dark-5">{{ $user->phone }}</td>
                            <td class="border-b dark:border-dark-5">{{ $user->created_at }}</td>
                            
                            <td class="border-b dark:border-dark-5">
                                <div class="flex">
                                    <a href="{{ route('users.edit', $user->id) }}" class="flex mr-3">
                                        <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit
                                    </a>
                                    {!! Form::open(['method' => 'DELETE', 'url' => 'admin/users/' . $user->id]) !!}
            
            <button type="submit" class="flex text-theme-6" onclick="return confirm('Are you sure?')"><i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Delete</button>
            
            {!! Form::close() !!}
                            </div>
                            </td>
                        </tr>
                    @endforeach
                    
                </tbody>
            </table>
            {{$users->links()}}
        </div>
    </div>
    
</div>
</div>
<!-- END: Basic Table -->

</div>

</div>     
</div>